= Maxwell Chibuogwu's Bio_Systems 534 Project

== Finding Open Reading Frames

[square]
* NAME

     orf_finder.py -- Finding the Open Reading Frames (ORFs)

* SYNOPSIS

     orf_finder.py [-h] [-s str] [-m int] [-o outfile] str

* DESCRIPTION

     This program 'orf_finder.py' will accept a text(nucleotide) sequence (DNA or RNA) from the command line or a file with sequences. It will then look for potential Open Reading Frames and write them to a named output file in FastA format. 
	 
	 The program will first convert the DNA sequence to RNA. Then, the potential open reading frames would start from the Default `AUG` codon or any of the specified codons given with `-s` or `--start`. It will also accept a minimum length of ORFs that should be found.
	 
	 At the end, the ORFs found will be printed in FastA format to a file or to the screen if no `outfile` is given. 

* EXIT STATUS

     If no ORFs are found, the program will report 'No ORFs in this sequence'.


* The program should handle a _DNA or RNA sequence_ as a text or in a _single file_ provided as a positional argument:

---
-s| --start: CODON to start reading

-m| --minlength: Minimum ORF length

-o| --outfile: where to write the ORFs

    $ ./orf_finder.py -h
   usage: orf_finder.py [-h]

---

Given no arguments, it should print a short usage statement:

----
$ ./orf_finder.py
usage: orf_finder.py [-h] [-s str] [-m int] [-o outfile] str
orf_finder.py: error: the following arguments are required: str

----
The program should reject a `--minlength` argument less than 20

----
$ ./orf_finder.py input.txt -m 15
usage: orf_finder.py [-h] [-s str] [-m int] [-o outfile] str
orf_finder.py: error: --minlength "15" must be greater than 20.
